jamesrowe1/ZAP

index.html
=> boiler html

index.html
Added the search bar and few cards
=> update on html and searchbar

index.html
Please confirm the html changes
=> added html buttons

index.html, script.js
=> save button

index.html, script.js
=> search function

index.html, script.js
updating dyn var and function for picture data
=> Dynamic pic

index.html, script.js
=> Revert "git stuff"

style.css
playing with background gradation
=> background experimentation

index.html, style.css
animated background fuzz screen
=> background

index.html
=> fuzz background

index.html
added links, still tinkering with it
=> added favicon link but still working on it

style.css
=> aboutustomato

index.html, script.js
add social media links in html - can be removed later if team prefers
=> initial set up share btn

script.js
=> Revert "initial set up share btn"

index.html, script.js, style.css
=> Share button

script.js
=> style button

aboutus.html
contact buttons that redirect you to contact page
=> contact link

style.css
=> Changing button

index.html, likes.html, style.css
=> Modal design

likes.html, style.css
=> Home page buttons
